/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pibanezl (https://sketchfab.com/hypermegadev)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-amp-5c4c4769394349d3a5d320ed46cc7db1
title: Old amp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes['lp_cajon_def001_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
          <mesh castShadow receiveShadow geometry={nodes['lp_cajon_def001_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          <mesh castShadow receiveShadow geometry={nodes.lp_cajon_def001_amp_0.geometry} material={materials.material} />
          <mesh castShadow receiveShadow geometry={nodes['lp_cajon_def001_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh castShadow receiveShadow geometry={nodes['lp_cajon_def001_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh castShadow receiveShadow geometry={nodes['lp_cajon_def001_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
